# Generated by Django 5.1.4 on 2025-01-02 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DotaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='choice_text',
            new_name='input_text',
        ),
    ]
